### ISSUE TITLE
ProgressView color change

### ISSUE THREAD

**Issue by nhjariwala** [alskipp/ASProgressPopUpView#8]
Hi I loved this library and thanks for such a awesome work. I have implemented it into my project and it works like charm. But I have facing some strange issue. 
I have used Tab on my project in which on my first tab I have used progressView into TableViewCell. When I run the project ProgressView display the same color that have been set by me it looks like below image.

![screen shot 2015-09-11 at 3 55 19 pm](https://cloud.githubusercontent.com/assets/11612197/9812908/729df594-589e-11e5-9381-2a46c021c6b9.png)

But When I changed my tab (means from 1st Tab to 2nd Tab and then back to 1st Tab) then the progress colour changed it looked like below image

![screen shot 2015-09-11 at 3 55 47 pm](https://cloud.githubusercontent.com/assets/11612197/9812923/a71a94c6-589e-11e5-9d01-d49376b043d3.png)

Don't know whats wrong with it.. Banging my head from last several hours. Thanks

**Comment by alskipp** [comment]
Hmm, that's a pain. Are you using animated colors, or is the popUpView a constant color throughout?

**Comment by alskipp** [comment]
If you're using animated colors, could you try the following quick hack: reset the animated colors when the tab changes?
`self.progressView.popUpViewAnimatedColors = … `

**Comment by nhjariwala** [comment]
No I am not using animated colors. Please have look my code

    func initProgressPopUp() {
        myProgressPopUpView.progress = 0
        myProgressPopUpView.popUpViewCornerRadius = 12.0
        myProgressPopUpView.font = UIFont(name: "Futura-CondensedExtraBold", size: 28)
        myProgressPopUpView.popUpViewColor = UIColor(red: 0.0/255.0, green: 184.0/255.0, blue: 226.0/255.0, alpha: 1)
    }

    
    func setProgress(destination: Double) {
        tar = Double(destination/100)
        progress()
    }
    
    func progress() {
        myProgressPopUpView.showPopUpViewAnimated(true)
        let TIMES = 0.05
        var progress = myProgressPopUpView.progress
        if progress < Float(tar) {
            progress += 0.005
            self.myProgressPopUpView.setProgress(progress, animated: true)
            var timer = NSTimer.scheduledTimerWithTimeInterval(TIMES,
                target: self,
                selector: Selector("progress"),
                userInfo: nil,
                repeats: false)
        }
    }

Thanks

**Comment by alskipp** [comment]
Does it help to set `autoAdjustTrackColor` to NO?

**Comment by nhjariwala** [comment]
Let me check it and let you know in 2 min

**Comment by nhjariwala** [comment]
It will change the color of my progressView. Now progressView look like this

![screen shot 2015-09-11 at 4 56 32 pm](https://cloud.githubusercontent.com/assets/11612197/9813785/404e4172-58a6-11e5-876d-5dc1fbb0bd41.png)

It look same when load first time and when tab switched.

**Comment by alskipp** [comment]
Ok, we're making progress ; )
Could you then set the `progressTintColor` to the appropriate color afterwards. This might fix the problem (though it is a bit of a hack).

**Comment by nhjariwala** [comment]
Bravo .... It works man .... you are life saviour  :+1:  

Thank you so much for your help.... ;)

**Comment by alskipp** [comment]
Glad it's working for you now : )
Though the problem you experienced is clearly a bug. I'll have to look into it. If you are able to post a demo project that demonstrates that problem it would be really helpful – understand if this is not possible though.

Al the best,
Al

**Comment by nhjariwala** [comment]
I will create demo project for you and send it to you soon .. But it will be in Swift version hope you don't mind about it.

**Comment by alskipp** [comment]
Swift is good :+1:

**Comment by nhjariwala** [comment]
Great .. I will send you soon. Thanks again
